// <auto-generated />
using AutoShop1.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AutoShop1.Migrations
{
    [DbContext(typeof(Auto_ShopContext))]
    partial class Auto_ShopContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AutoShop1.Models.AutoShop", b =>
                {
                    b.Property<int>("IdCar")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CarColor");

                    b.Property<string>("CarLocation");

                    b.Property<string>("CarName");

                    b.Property<string>("CarPower");

                    b.Property<string>("CarPrice");

                    b.Property<string>("CarTransmission");

                    b.Property<string>("Manifacture");

                    b.HasKey("IdCar")
                        .HasName("PK_Test");

                    b.ToTable("AutoShop");
                });
#pragma warning restore 612, 618
        }
    }
}
